<?php

namespace Tests;
use Illuminate\Support\Facades\DB;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    use CreatesApplication;

    private static $ranMigration=false;

    public function setUp()
    {
        parent::setUp();
        if(!self::$ranMigration)
        {
            $this->artisan("migrate:refresh");
            self::$ranMigration=true;
        }
        DB::beginTransaction();


    }

    public function tearDown()
    {
        DB::rollback();
        parent::tearDown(); // TODO: Change the autogenerated stub



    }
}
